name: festim-v2-review-env
channels:
  - conda-forge
  - defaults
dependencies:
  - festim==2.0a4
  - pip
  - pip:
    - git+https://github.com/festim-dev/foam2dolfinx
    - git+https://github.com/festim-dev/openmc2dolfinx

